apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: jmalloc/echo-server
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http-port
        containerPort: 8080
        protocol: TCP

